events {}

http {
  resolver 127.0.0.11 valid=10s ipv6=off;

  server {
    listen 80;

    location /api/ {
      set $web_api_upstream web-api:8000;
      rewrite ^/api/(.*)$ /$1 break;
      proxy_pass http://$web_api_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /gateway/ {
      set $agent_gateway_upstream agent-gateway:8000;
      rewrite ^/gateway/(.*)$ /$1 break;
      proxy_pass http://$agent_gateway_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
      set $web_ui_upstream web-ui:80;
      proxy_pass http://$web_ui_upstream;
    }
  }
}
